name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Building project
        run: mvn -B package --file pom.xml
      - name: Docker login
        run: docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.PAT }}
      - name: Build Docker image
        run: docker build . -t ${{ secrets.package }}
      - name: Publish Docker image
        run: docker push ${{ secrets.package }}
      - name: Login via ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.server }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Deploy
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.username }}@${{ secrets.server }} "bash ~/deploy.sh $GITHUB_ACTOR ${{ secrets.PAT }} ${{ secrets.package }}"
