name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Building project
        run: mvn -B package --file pom.xml
        env:
          DB_HOST: localhost
          DB_NAME: db
      - name: Docker login
        run: docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.PAT }}
      - name: Build Docker image
        run: docker build . -t ${{ secrets.PACKAGE }}
      - name: Publish Docker image
        run: docker push ${{ secrets.PACKAGE }}
      - name: Login via ssh
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Deploy
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.SERVER }} "bash ~/deploy.sh $GITHUB_ACTOR ${{ secrets.PAT }} ${{ secrets.PACKAGE }}"
